#!/usr/bin/env python

import sys
import os
import subprocess

def run():
    exe  = "/usr/bin/pantheon-files"
    cwd  = os.getcwd()
    path = os.path.expanduser("~")

    if len(sys.argv) >= 2:
    	path = sys.argv[1]
        
    	if path.startswith("file"):
			path = path[5:]

        if not os.path.isabs(path):
            path = os.path.join(os.getcwd(), path)

    cmd = [exe, path]
    subprocess.Popen(cmd)

run()