#!/usr/bin/env python

import sys
import os
import subprocess

def run():
    exe = "/opt/sublime_text/sublime_text"
    cwd = os.getcwd()
    cmd = [exe]

    if len(sys.argv) >= 2:
        path = sys.argv[1]

        if path.startswith("file"):
            path = path[5:]

        if not os.path.isabs(path):
            path = os.path.join(os.getcwd(), path)

        cmd = [exe, path]
    
    env = dict(os.environ)
    env['LD_PRELOAD'] = os.path.expanduser('~/.usrbin/libsubl-im.so')
    subprocess.Popen(cmd, env=env)

run()